version: '3'
services:
  seed:
    container_name: akka-demo_seed-1
    image: akka-demo
    ports:
      - '1800:1800'
    environment:
      CLUSTER_PORT: 1800
      CLUSTER_IP: seed
      SEED_PORT_1800_TCP_ADDR: seed
    networks:
      - akka-demo
  c1:
    image: akka-demo
    ports:
     - '1801:1801'
    environment:
      CLUSTER_PORT: 1801
      CLUSTER_IP: c1
      SEED_PORT_1800_TCP_ADDR: seed
    networks:
      - akka-demo
  c2:
    image: akka-demo
    ports:
     - '1802:1802'
    environment:
      CLUSTER_PORT: 1802
      CLUSTER_IP: c2
      SEED_PORT_1800_TCP_ADDR: seed
    networks:
      - akka-demo
networks:
  akka-demo: